#!/bin/bash

LOG_PATH=~/.time-mg-opc.csv  # TIME MG TIME TRACKER

echo ""
echo "Shortkeys:"
echo "- Answer action: ............... Space"
echo "- Skip card action: ............ CTRL + Space"
echo "- Skip level action: ........... PageUp"
echo "- Hide card action: ............ SHIFT + Space"
echo "- Right answer action: ......... L"
echo "- Wrong answer action: ......... H"
echo "- Right answer action + hide: .. SHIFT + L"
echo "- Wrong answer action + hide: .. SHIFT + H"
echo ""

if [ -e ~/opencal.lock ]
then
    zenity --error --title="Error" --text="OPC already run (~/opencal.lock)"
else
    touch ~/opencal.lock

    echo "opc-start,$(date --iso-8601='seconds')" >> ${LOG_PATH}  # TIME MG TIME TRACKER

    OPC=$(python -c "import opcgui.qt.main ; print(opcgui.qt.main.__file__)")

    # TODO: WORKAROUND https://forum.qt.io/topic/54802/linux-application-does-not-accept-keyboard-input/4
    QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb $OPC

    #./opcgui/qt/main.py

    echo "opc-stop,$(date --iso-8601='seconds')" >> ${LOG_PATH}  # TIME MG TIME TRACKER

    rm ~/opencal.lock
fi
